### PR TITLE
fix: migrate ot openapi-typescript and openapi-fetch

### LINKED ISSUE #565: Error `TypeError: Right-hand side of 'instanceof' is not an object` when creating registry service account or activating vm subscription
Telemetry shows rise of errors after v1.0.3 release:
- rdhat.redhredhat.redhat-authentication.signin, registry-configuration; TypeError: Right-hand side of 'instanceof' is not an objectat
- redhat.redhat-authentication.signin, subscription-activation; TypeError: Right-hand side of 'instanceof' is not an object

It seems not to be platform related, because it is reported on macOS, windows and linux.

The the stack for error should be reported to understand where it comes from.  Stack should be striped of user local folders before included into telemetry.

Depends on:
https://github.com/redhat-developer/redhat-javascript-rest-api-clients/issues/11

### PR DESCRIPTION
**Pull request by dgolovin**
Fix #565.

### CODE REVIEW

**Comment by benoitf** [comment]
hello,  have a question: why the gen files are included in the source code. Usually it's part of the build process where generated files are generated by a openapi-typescript call ?

https://github.com/containers/podman-desktop-extension-ai-lab/blob/bd01b12d498df52189afccba1bec14cd3982f081/packages/backend/package.json#L93

**Comment by dgolovin** [comment]
I like when I have everything tagged during release, even generated files, so I don't have to generate them when checking out tag or branch. But that is not critical and I can follow the the same pattern as AI Lab.

**Comment by dgolovin** [comment]
Applying fix for #636 is not enough to fix #565. The error from #565 still persists. We can do release only after this PR is merged.

**Review by benoitf — COMMENTED** [review]
LGTM but generated files should not be committed (as in other repositories) and there is a missing command to regenerate the files

File: src/rh-api/utils.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ ***********************************************************************/
+
+import type { Client } from 'openapi-fetch';
+
+export class ClientHolder<T extends object> {
+  protected client: Client<T, `${string}/${string}`>;
```
Comment (benoitf) [inline src/rh-api/utils.ts:22]: `${string}/${string}` should be extracted as a dedicated type to avoid copy/paste it multiple times

File: src/util.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /**********************************************************************
- * Copyright (C) 2024 Red Hat, Inc.
+ * Copyright (C) 2024 - 2025 Red Hat, Inc.
```
Comment (benoitf) [inline src/util.ts:2]:
```suggestion
 * Copyright (C) 2024-2025 Red Hat, Inc.
```

File: src/rh-api/registry-authorizer.ts [hunk 3]
```diff
@@ -0,0 +1,63 @@
+/**********************************************************************
+ * Copyright (C) 2024 - 2025 Red Hat, Inc.
```
Comment (dgolovin) [inline src/rh-api/registry-authorizer.ts:2]:
```suggestion
 * Copyright (C) 2024-2025 Red Hat, Inc.
```

File: src/rh-api/subscription.ts [hunk 4]
```diff
@@ -1,5 +1,5 @@
 /**********************************************************************
- * Copyright (C) 2024 Red Hat, Inc.
+ * Copyright (C) 2024 - 2025 Red Hat, Inc.
```
Comment (dgolovin) [inline src/rh-api/subscription.ts:2]:
```suggestion
 * Copyright (C) 2024-2025 Red Hat, Inc.
```

File: src/rh-api/utils.ts (hunk 1 above)
Comment (dgolovin) [reply src/rh-api/utils.ts]: This is default type, so it is not needed at all.

Comment (dgolovin) [reply src/rh-api/utils.ts]: I have removed it.

File: src/extension.spec.ts [hunk 5]
```diff
@@ -180,8 +180,18 @@ suite('signin command telemetry reports', () => {
...
+    vi.spyOn(podmanCli, 'getConnectionForRunningPodmanMachine').mockReturnValue({ 
+      providerId: '1',
+      connection: {
+        name: 'machine1',
+        type: 'podman',
+        endpoint: {
+          socketPath: '/path/to/the/socket',
+        },
+        status: ()=> 'started',
+      }
```
Comment (dgolovin) [inline src/extension.spec.ts:192]:
```suggestion
      },
```

**Comment by dgolovin** [comment]
> LGTM but generated files should not be committed (as in other repositories) and there is a missing command to regenerate the files

Updated PR and tested manually all combination creating and reusing API resources.

**Review by benoitf — APPROVED** [review]
I would have put generated source code in another sec folder ( like the other extensions) but can be follow up
