### PR TITLE
fix: do not ignore errors in podman cli calls

### LINKED ISSUE #116: Subscription activation failure not reported to the user
This for example happening on Windows where different vm image is uses and it has no rpm-tree cli command available, so the subscription manager installation fails, but task manager still reports it as successful.

### PR DESCRIPTION
**Pull request by dgolovin**
Fix #116.
Some problems does not get reported. For example on windows when trying to install subscription manager on old podman vm where there is no rpm-tree cli tool , `runInstallSubscriptionMangaer' is not going to report exception and login is shown as successful, but the subscription-managre is not installed and error is not reported.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -188,13 +188,14 @@ async function isSubscriptionManagerInstalled(): Promise<boolean> {
...
-  const exitCode = await runRpmInstallSubscriptionManager();
-  if (exitCode === undefined) {
-    throw new Error(
-      'Error running podman to install subscription-manager, please make sure podman machine is running!',
-    );
+  try {
+    const exitCode = await runRpmInstallSubscriptionManager();
+  } catch (err) {
+    const exitCode = (err as extensionApi.RunError).exitCode;
+    console.error(`Subscription manager installation returned exit code: ${exitCode}`);
```
Comment (vrothberg) [inline src/extension.ts:195]: Tiny nit: As a user, I'd be more interested in the error message than the exit code.
