### PR TITLE
fix: add telemetry reporting

### LINKED ISSUE #43: Send telemetry when creating container image registry service accounts and subscription activation keys
There should be telemetry send after tha API calls to create:
* container registry service account
* subscription activation key

Telemetry data should indicate if the call was successful or failed

Related to #35.

### PR DESCRIPTION
**Pull request by dgolovin**
Fix #43.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -352,13 +359,19 @@ export async function activate(context: extensionApi.ExtensionContext): Promise<
...
 
     if (failed.some(fail => fail)) {
       removeSession(currentSession.id); // if at least one fail, remove session
     }
+
+    TelemetryLogger.logUsage('redhat.authentication.signin', telemetryData);
+
   });
 
   const SignOutCommand = extensionApi.commands.registerCommand('redhat.authentication.signout', async () => {
```
Comment (slemeur) [inline src/extension.ts:377]: There should be an event on signout too

File: src/extension.ts [hunk 2]
```diff
@@ -352,13 +359,19 @@ export async function activate(context: extensionApi.ExtensionContext): Promise<
...
+        return true; // required to force Promise.all() call keep waiting for all not failed calls
+      });
 
     const failed = await Promise.all([registryAccess, vmActivation]); // wait for all fail or pass
 
     if (failed.some(fail => fail)) {
       removeSession(currentSession.id); // if at least one fail, remove session
     }
+
+    TelemetryLogger.logUsage('redhat.authentication.signin', telemetryData);
```
Comment (slemeur) [inline src/extension.ts:373]: For consistency and accuracy, I think the name of the event should be using the name of the extension:
`redhat.redhat-authentication`

Comment (jeffmaury) [reply src/extension.ts:373]: The extension id is added by the Podman Desktop API so not required here. signin should be enough

Comment (dgolovin) [reply src/extension.ts]: Updated logUsage call to use short event names like `signin`, `signout` and etc

File: src/podman-cli.ts [hunk 3]
```diff
@@ -89,6 +92,7 @@ export async function runRpmInstallSubscriptionManager(): Promise<number | undef
   } catch (err) {
     const exitCode = (err as extensionApi.RunError).exitCode;
     console.error(`Subscription manager installation returned exit code: ${exitCode}`);
+    TelemetryLogger.logError('SubscriptionManagerInstallationError', {error: String(err)});
```
Comment (dgolovin) [inline src/podman-cli.ts:95]:
```suggestion
    TelemetryLogger.logError('subscriptionManagerInstallationError', {error: String(err)});
```

File: src/extension.ts [hunk 4]
```diff
@@ -319,7 +323,10 @@ export async function activate(context: extensionApi.ExtensionContext): Promise<
         },
       )
       .then(() => false)
-      .catch(() => true); // required to force Promise.all() call keep waiting for all not failed calls
+      .catch((error) => {
+        telemetryData['registryAccessConfigurationError'] = String(error);
```
Comment (dgolovin) [inline src/extension.ts:327]:
```suggestion
```
not required, because it is going to be recorded in podman-cli.ts

File: src/extension.ts [hunk 5]
```diff
@@ -352,20 +359,27 @@ export async function activate(context: extensionApi.ExtensionContext): Promise<
         },
       )
       .then(() => false)
-      .catch(() => true); // required to force Promise.all() call keep waiting for all not failed calls
+      .catch((error) => {
+        telemetryData['vmSubscriptionActivationError'] = String(error);
```
Comment (dgolovin) [inline src/extension.ts:363]:
```suggestion
```

not required, because it is going to be recorded in podman-cli.ts

File: src/extension.ts [hunk 6]
```diff
@@ -302,6 +304,8 @@ export async function activate(context: extensionApi.ExtensionContext): Promise<
   context.subscriptions.push(providerDisposable);
 
   const SignInCommand = extensionApi.commands.registerCommand('redhat.authentication.signin', async () => {
+    const telemetryData = {};
```
Comment (dgolovin) [inline src/extension.ts:307]:
```suggestion
    const telemetryData = {
      successful: true,
    };
```

File: src/extension.ts [hunk 7]
```diff
@@ -352,20 +359,27 @@ export async function activate(context: extensionApi.ExtensionContext): Promise<
...
+        telemetryData['vmSubscriptionActivationError'] = String(error);
+        return true; // required to force Promise.all() call keep waiting for all not failed calls
+      });
 
     const failed = await Promise.all([registryAccess, vmActivation]); // wait for all fail or pass
 
     if (failed.some(fail => fail)) {
       removeSession(currentSession.id); // if at least one fail, remove session
     }
+
```
Comment (dgolovin) [inline src/extension.ts:372]:
```suggestion
      telemetryData.successful = false;
    }

```

File: src/extension.ts [hunk 8]
```diff
@@ -352,20 +360,27 @@ export async function activate(context: extensionApi.ExtensionContext): Promise<
...
+      });
 
     const failed = await Promise.all([registryAccess, vmActivation]); // wait for all fail or pass
 
     if (failed.some(fail => fail)) {
       removeSession(currentSession.id); // if at least one fail, remove session
+      telemetryData.successful = false;
     }
+
+    TelemetryLogger.logUsage('signin', telemetryData);
```
Comment (benoitf) [inline src/extension.ts:374]: I think we're missing lot of data in telemetryData

here it's only successful yes/no

I would expect the time it has taken, in case of failure, which step succeed/failed.


did we have to restart and how many restart

at which step the user stopped the flow

for example it's different if user aborted if no podman machine was running vs error in doing the task
did we have a PodmanMachineRunning ?

was isSubscriptionManagerInstalled already installed ?

Was it registryAccess part, vmActivation part

for each step, the time it took as well.

Then about the session, probably need some data (about the user being authenticated
I don't know what data we have but maybe number about some fields of the user (counter)

Comment (dgolovin) [reply src/extension.ts:376]: @benoitf @slemeur would be possible to fix all of that as follow up issues? I have added part of it and working on tests right now, but it will take some time to implement.

Comment (vrothberg) [reply src/extension.ts:376]: I think that's fair.  We had a meeting on the telemetry issue (https://github.com/redhat-developer/podman-desktop-redhat-account-ext/issues/43#issuecomment-1997959842) where these details did not come up.  So I guess we under-specified the requirements initially.

Merging the PR and trying to get as far as possible until the deadline is OK for me.

**Comment by dgolovin** [comment]
@benoitf 

> I think we're missing lot of data in telemetryData
> I would expect the time it has taken, in case of failure, which step succeed/failed.

> did we have to restart and how many restart

It is always one restart if needed at all, I can send start and stop command outcome.

> at which step the user stopped the flow

User cannot stop the flow right now, it keeps going until it is finished with failure or success.

> for example it's different if user aborted if no podman machine was running vs error in doing the task
did we have a PodmanMachineRunning ?

I have added error messages to telemetry for registry configuration and subscription activation

> was isSubscriptionManagerInstalled already installed ?

Follow up issue #113 created

> Was it registryAccess part, vmActivation part

added field with error message for each part

> for each step, the time it took as well.

Follow up issue #114 created

> Then about the session, probably need some data (about the user being authenticated
> I don't know what data we have but maybe number about some fields of the user (counter)

I need clarification for this. What king of tracking we want to do here. Number of logins for specific user? Session duration?
