### PR TITLE
fix: if username and email not available show 'email not found'

### LINKED ISSUE #59: Signed in as "user@example.com"
When signed into the Podman Desktop "Authentication" "Red Hat SSO" extension, I see "user.example.com" as my user name:

image

I would expect it to say: "swalter@redhat.com"

I logged in via Red Hat SSO.

```
$ podman images | grep account-ext
quay.io/redhat-developer/podman-desktop-redhat-account-ext      0.0.2-alpha.2      c7bd1362e9ba  13 days ago   2.12 MB
```

```
$ flatpak list | grep Podman
Podman Desktop                 io.podman_desktop.PodmanDesktop               1.7.1             stable               system
```

### PR DESCRIPTION
**Pull request by dgolovin**
fix #59.

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Review by benoitf — APPROVED** [review]

File: src/authentication-service.ts [hunk 1]
```diff
@@ -445,7 +445,7 @@ export class RedHatAuthenticationService {
       scope: scope,
       account: {
         id: claims.sub,
-        label: claims.preferred_username || claims.email || 'user@example.com',
+        label: claims.preferred_username || claims.email || 'email not found',
```
Comment (benoitf) [inline src/authentication-service.ts:448]:
```suggestion
        label: claims.preferred_username ?? claims.email ?? 'email not found',
```

Comment (dgolovin) [reply src/authentication-service.ts:448]: In the cases where `claim.preferred_username === ''` and/or `claim.email === ''` page would not show anything in place of username. It would show 'email not found' only if both claims do not defined in the token.

For me '' equals 'email not found'.
