### PR TITLE
fix: pass urlProtocol as query parameter to sucess.html page

### LINKED ISSUE #1070: xdg redirect should be parametrized using product.json information
When the browser page after successful login is shown, the redirect handle uses hardcoded `Podman Desktop` app name to open. We should use parametrized handle name based on ie. `product.json` configuration file. 

For example if I initiate the redirect from my testing electron app based on podman-desktop, it opens podman-desktop installed app instead of my testing instance.

### PR DESCRIPTION
**Pull request by dgolovin**
This fixes #1070 by reading urlProtocol form env.urlProtocol and passing it as a query parameter to success.html page.

It depends on:
* https://github.com/podman-desktop/podman-desktop/pull/16965
* https://github.com/podman-desktop/podman-desktop/pull/16964

### CODE REVIEW

File: src/authentication-service.ts [hunk 1]
```diff
@@ -377,7 +377,7 @@ export class RedHatAuthenticationService {
       if ('err' in redirectReq) {
         const { err, res } = redirectReq;
         res.writeHead(302, {
-          Location: `/?service=${this.config.serviceId}&error=${encodeURIComponent((err as Error)?.message || 'Unknown error')}`,
+          Location: `/?service=${this.config.serviceId}&error=${encodeURIComponent((err as Error)?.message || 'Unknown error')}&protocol=${env.urlProtocol}`,
```
Comment (cdrage) [inline src/authentication-service.ts]: how are we getting `env.urlProtocol` ? is this coming from the API?

if so, we should add a way to fallback if the API does not have this, or else the protocol is blank (ex. downstream product)

**Review by cdrage — CHANGES_REQUESTED** [review]
we should add fallbacks if env.urlProtocol does not exist if this is extension is installed on a system that does not have it.

File: src/authentication-service.ts (hunk 1 above)
Comment (dgolovin) [reply src/authentication-service.ts]: when master branch for podman-desktop/packages/extension-api is published, I am going to update the version for @podman-desktop/api and it will guarantee that the property is there. Until then the PR cannot be merged.

I have [workaround PR](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/1130) instead that allow to set urlPtotocol for the www/index.html page during the build with default to podman-desktop.

Comment (dgolovin) [reply src/authentication-service.ts]: @cdrage added 'podman-desktop' as default in case env.urlProtocul is not defined.

**Review by axel7083 — APPROVED** [review]

**Review by feloy — APPROVED** [review]

**Review by SoniaSandler — APPROVED** [review]

File: src/authentication-service.ts [hunk 2]
```diff
@@ -38,6 +38,8 @@ import { createServer, startServer } from './authentication-server';
 import type { AuthConfig } from './configuration';
 import Logger from './logger';
 
+const urlProtocol = (env as { urlProtocol?: string }).urlProtocol ?? 'podman-desktop';
```
Comment (cdrage) [inline src/authentication-service.ts:41]: Just so I understand, if API does not have urlProtocol it will fallback to `podman-desktop`, so basically anything 1.26.2 and below, it'll default to `podman-desktop`, but api `1.27` and above, it will?

don't we have to update 1.27.0 when it's released / update it here in the PR if I'm understanding this correctly? so that it will get env.urlProtocol correctly?

https://github.com/redhat-developer/podman-desktop-redhat-account-ext/blob/main/package.json#L54

**Review by cdrage — CHANGES_REQUESTED** [review]

File: src/authentication-service.ts (hunk 2 above)
Comment (dgolovin) [reply src/authentication-service.ts:41]: @cdrage 

> Just so I understand, if API does not have urlProtocol it will fallback to podman-desktop, so basically anything 1.26.2 and below, it'll default to podman-desktop, but api 1.27 and above, it will?

correct.

> don't we have to update 1.27.0 when it's released / update it here in the PR if I'm understanding this correctly? so that it will get env.urlProtocol correctly?

We should update it, because it is pinned to 1.14.1 right now in pnpm-lock.yaml file.

nothing can prevent extension to be installed in podman desktop through `Custom extension ...`. engines section in package.json is just a declaration. 

We can only add `podmanDesktopVersion="^1.27.0" when publishing it to the catalog to prevent installations on PD versions below 1.27.

Comment (dgolovin) [reply src/authentication-service.ts:41]: The PR cannot be merged because @podman-desktop/podman-extension-api@1.27.0 has not been published yet.

Comment (dgolovin) [reply src/authentication-service.ts:41]: @cdrage  I've updated engines and podman-extension-api package to ^1.27.0 and build is going to fail until 1.27.0 is published.

Comment (dgolovin) [reply src/authentication-service.ts:41]: updated to ^1.27.0 in package.json, but pnpm-lock.still needs to be updated after it is published.

File: package.json [hunk 3]
```diff
@@ -50,8 +50,8 @@
     "test:e2e": "cross-env E2E_TESTS=true DEBUG=pw:channel:response,pw:channel:event npm run test:e2e:setup npx playwright test tests/src"
   },
   "dependencies": {
-    "@podman-desktop/api": "^1.14.1",
-    "@podman-desktop/podman-extension-api": "^1.26.2",
+    "@podman-desktop/api": "^1.27.0",
+    "@podman-desktop/podman-extension-api": "^1.27.0",
```
Comment (dgolovin) [inline package.json]:
```suggestion
    "@podman-desktop/api": "1.27.0-next.202604210820-677f704",
    "@podman-desktop/podman-extension-api": "1.27.0-next.202604210820-677f704",
```

**Review by cdrage — CHANGES_REQUESTED** [review]
ACK. LGTM, but pending:

```
    "@podman-desktop/api": "1.27.0-next.202604210820-677f704",
    "@podman-desktop/podman-extension-api": "1.27.0-next.202604210820-677f704",
```

being updated after release is out.

Keep in mind that because of: https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/1118/changes#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R12

the extension in the catalog will only be installable on PD 1.27.0 and above.... since https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/1118/changes#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L12 will now be a large version bump.

**Comment by dgolovin** [comment]
> Keep in mind that because of: https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/1118/changes#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R12
> 
> the extension in the catalog will only be installable on PD 1.27.0 and above.... since https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/1118/changes#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L12 will now be a large version bump.

## Extension Install Entry Points & `engines["podman-desktop"]` Version Check

### Entry Points for Installing Extensions via Podman Desktop UI

#### 1. "Install Custom Extension" Button (Extensions page)

**Component:** [`InstallManuallyExtensionModal.svelte`](https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte#L44-L56)

User enters an OCI image name manually and clicks **Install**.
Calls `window.extensionInstallFromImage()` → IPC `extension-installer:install-from-image` → [`extension-installer.ts`](https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/install/extension-installer.ts#L126-L140)

**`engines["podman-desktop"]` check:** ❌ **None.**
The installer only checks for the OCI image label `io.podman-desktop.api.version` to confirm it is a valid Podman Desktop extension. The `engines` field in the extension's `package.json` is never read or validated.

---

#### 2. Catalog / Featured "Install" Button (Extensions page)

**Components (call chain):**
- [`FeaturedExtensionDownload.svelte`](https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/featured/FeaturedExtensionDownload.svelte#L44) — actual install trigger, also used by:
- [`CatalogExtension.svelte`](https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/extensions/CatalogExtension.svelte#L63)
- [`CatalogExtensionList.svelte`](https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/extensions/CatalogExtensionList.svelte#L53)
- [`EmbeddableCatalogExtensionList.svelte`](https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/extensions/EmbeddableCatalogExtensionList.svelte)

Also calls `window.extensionInstallFromImage()` → same backend path as above.

**`engines["podman-desktop"]` check:** ⚠️ **Indirect — from catalog metadata, not the extension's `package.json`.**

Version filtering happens _before the Install button is shown_, in [`extensions-catalog.ts`](https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/extension/catalog/extensions-catalog.ts#L156-L164).
It uses `semver.satisfies()` against `version.podmanDesktopVersion` from the **catalog JSON** — this is a separate field maintained in the catalog, independent of the extension's own `engines` declaration.

---

#### 3. Dev-Mode Folder Loading (Developer settings)

**Code:** [`extension-development-folders.ts`](https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/extension/extension-development-folders.ts#L142-L147)

Loads an extension from a local folder path. Not a traditional install, but another way extensions enter the loader.

**`engines["podman-desktop"]` check:** ⚠️ **Presence only — value is never semver-validated.**
The field must exist (not be `undefined`), but the version range string (e.g. `^1.10.0`) is ignored entirely.

---

### Summary Table

| Entry Point | Reads `engines["podman-desktop"]`? | Semver-validates the value? |
|---|---|---|
| [Install Custom Extension (manual OCI image)](https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte) | ❌ No | ❌ No |
| [Catalog / Featured Install button](https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/featured/FeaturedExtensionDownload.svelte) | ❌ No | ⚠️ Catalog's own `podmanDesktopVersion` field is used instead |
| [Dev-mode folder load](https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/extension/extension-development-folders.ts) | ⚠️ Presence check only | ❌ No |

> **Conclusion:** The `engines["podman-desktop"]` value in an extension's `package.json` (e.g. `"^1.10.0"`) is **never semver-validated** at install or load time in any flow. It serves as documentation only. The only real version gate is the catalog's `podmanDesktopVersion` field, which controls which extension versions are shown in the catalog UI.

**Review by cdrage — APPROVED** [review]
